=== Panelota/M04/XSD/leyenda/c.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="leyenda">
    <xs:complexType>
      <xs:sequence>

        <xs:element name="dragones">
          <xs:complexType>
            <xs:sequence>

              <xs:element name="dragon" maxOccurs="unbounded">
                  <xs:complexType>
                    <xs:sequence>

                      <xs:element name="ataqueDragon">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="poder" type="xs:string"/>
                            </xs:sequence>
                            <xs:attribute name="porcentaje"/>
                          </xs:complexType>
                        </xs:element>

                        <xs:element name="princesaHechicera">
                            <xs:complexType>
                              <xs:all>
                                <xs:element name="nombrePrincesa" type="xs:string"/>
                                
                                 <xs:element name="colorMagia">
                                    <xs:complexType>
                                      <xs:sequence>
                                        <xs:element name="luminosidad" type="xs:string"/>
                                      </xs:sequence>
                                     <xs:attribute name="color">
                                        <xs:simpleType>
                                          <xs:restriction base="xs:string">
                                            <xs:pattern value="negre|vermell|verd|blanc"/>
                                          </xs:restriction>
                                        </xs:simpleType>
                                        </xs:attribute>
                                    </xs:complexType>
                                  </xs:element>

                                    <xs:element name="nombreRosaConjuros" minOccurs="0">
                                        <xs:complexType>
                                          <xs:sequence>
                                            <xs:element name="calidadConjuros" type="xs:string"/>
                                          </xs:sequence>
                                           <xs:attribute name="cantidadConjuros"/>
                                        </xs:complexType>
                                      </xs:element>

                              </xs:all>
                            </xs:complexType>
                          </xs:element>

                    </xs:sequence>
                  <xs:attribute name="porcentaje"/>
                  </xs:complexType>
                </xs:element>

            </xs:sequence>
          </xs:complexType>
        </xs:element>
  
        <xs:element name="caballeros">
          <xs:complexType>
            <xs:sequence>

              <xs:element name="caballero" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>

                    <xs:element name="defensaCaballero">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="fuente" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="porcentaje"/>
                      </xs:complexType>
                    </xs:element>

                  </xs:sequence>
                </xs:complexType>
              </xs:element>

            </xs:sequence>
          </xs:complexType>
        </xs:element>

      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Panelota/M04/XSD/leyenda/c.xml
<?xml version="1.0" encoding="UTF-8"?>
<leyenda xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="c.xsd">
   <dragones>
     <dragon>
       <ataqueDragon porcentaje="30">
          <poder>3</poder>
       </ataqueDragon>
       <princesaHechicera>
         <nombrePrincesa>
           Sonja
         </nombrePrincesa>
         <colorMagia color="red">
            <luminosidad>8</luminosidad>
         </colorMagia>
         <nombreRosaConjuros cantidadConjuros="10">
            <calidadConjuros>6</calidadConjuros>
         </nombreRosaConjuros>
       </princesaHechicera>
     </dragon>
     <dragon>
       <ataqueDragon porcentaje="80">
          <poder>8</poder>
       </ataqueDragon>
       <princesaHechicera>
         <colorMagia color="negre">
            <luminosidad>0</luminosidad>
         </colorMagia>
         <nombrePrincesa>
           Morgana
         </nombrePrincesa>
       </princesaHechicera>
     </dragon>
   </dragones>
   <caballeros>
     <caballero>
       <defensaCaballero porcentaje="60">
           <fuente>hierro</fuente>
       </defensaCaballero>
     </caballero>
     <caballero>
       <defensaCaballero porcentaje="50">
            <fuente>hierro</fuente>
       </defensaCaballero>
     </caballero>
     <caballero>
       <defensaCaballero porcentaje="95">
            <fuente>hierro</fuente>
       </defensaCaballero>
     </caballero>
   </caballeros>
</leyenda>
