=== Panelota/M04/Eduard/UF1NF1A6_Activitats_DTD/e1.dtd
<!ELEMENT llibres (llibre+)>
<!ELEMENT llibre (codi,titol,editorial,edicio,isbn,pagines,autor)>
<!ELEMENT codi (#PCDATA)>
<!ELEMENT titol (#PCDATA)>
<!ELEMENT editorial (#PCDATA)>
<!ELEMENT edicio (#PCDATA)>
<!ELEMENT isbn (#PCDATA)>
<!ELEMENT pagines (#PCDATA)>
<!ELEMENT autor (#PCDATA)>

=== Panelota/M04/Eduard/UF1NF1A6_Activitats_DTD/e1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE llibres SYSTEM "e1.dtd">

<llibres>
    <llibre>
      <codi></codi>
      <titol></titol>
      <editorial></editorial>
      <edicio></edicio>
      <isbn>I</isbn>
      <pagines></pagines>
      <autor></autor>
    </llibre>
</llibres>
