=== Panelota/M04/Eduard/UF1NF1A6_Activitats_DTD/e4.dtd
<!ELEMENT concesionari (segonama+)>
<!ELEMENT segonama (codi, marca, model, potencia, places, portes)>
<!ELEMENT codi (#PCDATA)>
<!ELEMENT marca (#PCDATA)>
<!ELEMENT model (#PCDATA)>
<!ELEMENT potencia (#PCDATA)>
<!ELEMENT places (#PCDATA)>
<!ELEMENT portes (#PCDATA)>

=== Panelota/M04/Eduard/UF1NF1A6_Activitats_DTD/e4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE concesionari SYSTEM "e4.dtd">

<concesionari>
    <segonama>
      <codi>9876</codi>
      <marca>SEAT</marca>
      <model>LEON</model>
      <potencia>120</potencia>
      <places>5</places>
      <portes>5</portes>
    </segonama>
    <segonama>
      <codi>5463</codi>
      <marca>TOYOTA</marca>
      <model>AURIS</model>
      <potencia>136</potencia>
      <places>5</places>
      <portes>5</portes>
    </segonama>
    <segonama>
      <codi>3215</codi>
      <marca>TOYOTA</marca>
      <model>CELICA</model>
      <potencia>280</potencia>
      <places>2</places>
      <portes>3</portes>
    </segonama>
    <segonama>
      <codi>3987</codi>
      <marca>FORD</marca>
      <model>MUSTANG</model>
      <potencia>350</potencia>
      <places>5</places>
      <portes>5</portes>
    </segonama>
</concesionari>
