=== Panelota/M04/Eduard/AnnaMasanaExerciciXSD/companyiaelectrica.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="companyia-electrica">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="soci" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="nom"/>
              <xs:element name="cognoms">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="c" maxOccurs="unbounded" minOccurs="0"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Panelota/M04/Eduard/AnnaMasanaExerciciXSD/companyiaelectrica.xml
<?xml version="1.0" encoding="UTF-8"?>
<companyia-electrica xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="companyiaelectrica.xsd">
    <soci>
      <nom>joan</nom>
      <cognoms><c>caspar</c><c>fos</c></cognoms>
    </soci>
    <soci>
      <nom>flor</nom>
      <cognoms><c>fdez</c><c>artal</c></cognoms>
    </soci>
</companyia-electrica>
