=== Panelota/M04/dtd xml/BancNacional.dtd
<!ELEMENT BancNacional (compte+)>
<!ELEMENT compte (titular, adreca, mobil?, numero_compte_corrent,saldo, deutor?)>
<!ELEMENT titular (#PCDATA)>
<!ELEMENT adreca (#PCDATA)>
<!ELEMENT mobil (#PCDATA)>
<!ELEMENT numero_compte_corrent (#PCDATA)>
<!ELEMENT saldo (#PCDATA)>
<!ELEMENT deutor (#PCDATA)>
<!ATTLIST compte dni ID #REQUIRED>
<!ATTLIST saldo moneda (euros|dÃ²lars) #REQUIRED>

=== Panelota/M04/dtd xml/BancNacional.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE BancNacional SYSTEM "BancNacional.dtd">
<BancNacional>
    <compte dni="_34124">
      <titular></titular>
      <adreca></adreca>
      <numero_compte_corrent></numero_compte_corrent>
      <saldo moneda="euros">1000</saldo>
    </compte>
    <compte dni="_34235">
      <titular></titular>
      <adreca></adreca>
      <numero_compte_corrent></numero_compte_corrent>
      <saldo moneda="dòlars">0</saldo>
      <deutor></deutor>
    </compte>
</BancNacional>
