=== Panelota/M04/XSD/netflix.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="canal">
    <xs:complexType>
      <xs:sequence>
      
      <xs:element name="series">
      <xs:complexType>
        <xs:sequence>
          <xs:element name="serie" maxOccurs="unbounded">
            <xs:complexType>
              <xs:sequence>
                <xs:attribute name="idioma" type="xs:string"/>
                <xs:attribute name="valoracio" type="xs:string"/>
                       <xs:element name="titulo" type="xs:string"/>
                       <xs:element name="año" type="xs:string"/>
                        <xs:element name="reparto" type="xs:string"/>
                       <xs:element name="capitulo" maxOccurs="unbounded"/>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
          </xs:sequence>
      </xs:complexType>
    </xs:element>
    
      <xs:element name="peliculas">
            <xs:complexType>
              <xs:sequence>
                <xs:attribute name="idioma" type="xs:string"/>
                <xs:attribute name="valoracio" type="xs:string"/>
                       <xs:element name="titulo" type="xs:string"/>
                       <xs:element name="año" type="xs:string"/>
                        <xs:element name="reparto"/>
                             <xs:complexType>
                                <xs:all>
                                  <xs:element name="actriu" type="xs:string"/>
                                  <xs:element name="actor" type="xs:string" maxOccurs="unbounded"/>
                                </xs:all>
                              </xs:complexType>
                            </xs:element>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
        </xs:sequence>
      <xs:attribute name="nom" type="xs:string"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Panelota/M04/XSD/netflix.xml
<?xml version="1.0" encoding="UTF-8"?>
<canal nom="netflix" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="netflix.xsd">
      <series>
            <serie idioma="JAP" valoracio="3">
                  <titulo>Ataque a los titanes</titulo>
                  <año>2015</año>
                  <reparto></reparto>
                  <capitulo/>
                  <capitulo/>
            </serie>
            <serie  idioma="EN" valoracio="5">
                  <titulo>The end of the fuck&apos;g world</titulo>
                  <año>2017</año>
                  <reparto></reparto>
                  <capitulo/>
                  <capitulo/>
                  <capitulo/>
                  <capitulo/>
                  <capitulo/>
                  <capitulo/>
            </serie>
      </series>
      <peliculas>
            <pelicula idioma="ES" valoracio="5">
                  <titulo>Bandersnach</titulo>
                  <año>2018</año>
                  <reparto>
                        <actor>a</actor>
                        <actriz>d</actriz>
                  </reparto>
            </pelicula>
            <pelicula idioma="EN" valoracio="1">
                  <titulo>Lucas &apos; CO</titulo>
                  <año>2010</año>
                  <reparto>
                    <actriz>e</actriz>
                    <actor>f</actor>
                  </reparto>
            </pelicula>
      </peliculas>
</canal>
